name: Secure RDP

on: workflow_dispatch

jobs:
  secure-rdp:
    runs-on: windows-latest
    steps:
      - name: Configure Core RDP Settings
        run: |
          # Enable Remote Desktop and disable Network Level Authentication
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Create RDP User with Secure Password
        run: |
          Add-Type -AssemblyName System.Security
          $rdpUser = "RDP"
          $rdpPass = "P@ssw0rd123!"
          $secPass = ConvertTo-SecureString $rdpPass -AsPlainText -Force
          New-LocalUser $rdpUser -Password $secPass -FullName "RDP User" -Description "Temporary RDP Access" -ErrorAction SilentlyContinue
          Add-LocalGroupMember -Group "Administrators" -Member $rdpUser
          net user $rdpUser /active:yes

      - name: Install Tailscale
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList @("/i", "$installerPath", "/quiet", "/norestart") -Wait

      - name: Establish Tailscale Connection
        run: |
          & "C:\Program Files (x86)\Tailscale IPN\tailscale.exe" up --authkey $env:TAILSCALE_AUTHKEY --hostname github-rdp --accept-routes --accept-dns
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Verify RDP Accessibility
        run: |
          $ts = "C:\Program Files (x86)\Tailscale IPN\tailscale.exe"
          $ip = & $ts ip -4
          Write-Host "`n=== RDP ACCESS ==="
          Write-Host "Address: $ip"
          Write-Host "Username: RDP"
          Write-Host "Password: P@ssw0rd123!"
          Write-Host "==================`n"

      - name: Maintain Connection
        run: |
          while ($true) {
            Write-Host "[$(Get-Date)] RDP Active - Use Ctrl+C in workflow to terminate"
            Start-Sleep -Seconds 300
          }
